version: '3'

services:
    tbb-apache:
        build: ./images/nginx
        container_name: tbb-apache
        restart: always
        image: tbb-apache
        restart: always
        ports:
            - "80:8080"
        volumes:
            - ../data/etc/apache2/conf.d:/etc/apache2/conf.d
            - ../data/var/www:/var/www:rw
        links:
            - tbb-php

    tbb-php:
        build: ./images/php-fpm
        container_name: tbb-php
        restart: always
        image: tbb-php
        restart: always
        ports: 
            - "9000:9000"
        volumes:
            - ../data/var/www:/var/www:rw

    tbb-mysql:
      image: mariadb:5.5
      container_name: tbb-mysql
      restart: always
      volumes:
        - /var/mysql:/var/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root

    dockerUi:
      image: dockerui/dockerui
      restart: always
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      ports:
          - "5000:5050"